### PR TITLE
commenting out pandas writing to Excel

### PR DESCRIPTION
**Pull request by PatMyron**
## What does this PR do?

essentially reverting https://github.com/salesforce/aws-allowlister/pull/37 to fix https://github.com/salesforce/aws-allowlister/issues/88

## What gif best describes this PR or how it makes you feel?

panda

[//]: # (Encouraged: Insert an appropriate gif/meme to brighten up your reviewer's day.)

## Completion checklist

- [x] tested in my fork: https://github.com/PatMyron/aws-allowlister/pull/3
- [x] [Unit tests, Pylint, security testing, and Integration tests are passing.](https://github.com/salesforce/aws-allowlister/actions). GitHub actions does this automatically
- [x] The pull request has been appropriately labeled using the provided PR labels
- [x] signed the CLA, does that CLA check need to be re-run? @kmcquade

### CODE REVIEW

**Comment by kmcquade** [comment]
@PatMyron is there a reason for this?

**Comment by PatMyron** [comment]
@kmcquade to fix #88 (gets cron updating data again); currently fails with `ModuleNotFoundError: No module named 'pandas'`

spent hours trying to fix `.xlsx` writing instead, but `.csv` seems sufficient if `.xlsx` causes that much trouble

**Comment by kmcquade** [comment]
It won't return the module not found thing if you run `pipenv install --dev` first :)

**Comment by PatMyron** [comment]
Has been running into that even after `pipenv install --dev`:
https://github.com/salesforce/aws-allowlister/runs/4823542865?check_suite_focus=true

**Pull request merged**
