### PR TITLE
Add schedule to update database

### LINKED ISSUE #72: Add automatic updater via GitHub actions
This should:
* Run `make update-data`
* Run `make generate-examples`
* Create a PR with the updates (suggested: use https://github.com/peter-evans/create-pull-request). Example: https://github.com/salesforce/policy_sentry/blob/master/.github/workflows/update.yml

### PR DESCRIPTION
**Pull request by danquack**
## What does this PR do?
Updates the database every morning. Closes #72 

[//]: # (Required: Describe the effects of your pull request in detail. If
multiple changes are involved, a bulleted list is often useful.)

## What gif best describes this PR or how it makes you feel?
updates

[//]: # (Encouraged: Insert an appropriate gif/meme to brighten up your reviewer's day.)

## Completion checklist

- [x] Additions and changes have unit tests
- [x] [Unit tests, Pylint, security testing, and Integration tests are passing.](https://github.com/salesforce/aws-allowlister/actions). GitHub actions does this automatically
- [x] The pull request has been appropriately labeled using the provided PR labels

### CODE REVIEW

**Comment by danquack** [comment]
Screen Shot 2021-04-21 at 2 23 37 PM
Appears there was an error with the Eula, but I signed it.

**Comment by kmcquade** [comment]
@danquack - thanks for the contribution! Should it really update every morning?

**Comment by danquack** [comment]
Screen Shot 2021-04-21 at 2 26 03 PM Looks like there's an error with the CLA

**Comment by danquack** [comment]
@kmcquade the issue wasn't clear on what the time frame of the cron should be. I live the mindset by let the computers check often so I don't have to, but I think it really depends on salesforce decision of cost of runners and personal preference.

**Comment by kmcquade** [comment]
Let's do it every 2 weeks. Less wait time than monthly, but not so often that it adds significant effort or time spent maintaining

**Comment by danquack** [comment]
@kmcquade works for me! Theres always that workflow dispatch too in case you see something yourself and just want to run the job.

**Pull request merged**
