### PR TITLE
added acm-pca under Certificate Manager

### PR DESCRIPTION
**Pull request by pkaeding**
## What does this PR do?

[//]: # (Required: Describe the effects of your pull request in detail. If
multiple changes are involved, a bulleted list is often useful.)

Adds `acm-pca` under the umbrella of `acm`. Our AWS TAM confirmed that it is covered as part of ACM for compliance purposes.

## What gif best describes this PR or how it makes you feel?

[//]: # (Encouraged: Insert an appropriate gif/meme to brighten up your reviewer's day.)

## Completion checklist

- [ ] Additions and changes have unit tests
- [ ] [Unit tests, Pylint, security testing, and Integration tests are passing.](https://github.com/salesforce/aws-allowlister/actions). GitHub actions does this automatically
- [ ] The pull request has been appropriately labeled using the provided PR labels

### CODE REVIEW

**Comment by pkaeding** [comment]
I just signed the CLA, but I did see an error at one point. If I try signing again, though, it tells me I already signed. Is there anything more I should do there?

**Comment by jdyke** [comment]
> I just signed the CLA, but I did see an error at one point. If I try signing again, though, it tells me I already signed. Is there anything more I should do there?

No, same thing happened to me. Future PRs will reflect your CLA! It may also update here if someone pushes a commit. I can take a look at this if @kmcquade doesn't mind. 

Thanks for the PR!!

**Comment by pkaeding** [comment]
> It may also update here if someone pushes a commit

Cool, that worked. Thanks @jdyke!

**Comment by kmcquade** [comment]
@jdyke sure feel free!

**Comment by jdyke** [comment]
LGTM, thanks for the add!

**Pull request merged**
